version: '3.8'

services:
  postgres:
    image: postgres:17-alpine

    container_name: spacechat-postgres

    environment:
      POSTGRES_DB: tcpchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: spacechat-server

    build: 
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
      
    depends_on:
      - postgres

volumes:
  postgres_data: